// @generated by codegen — DO NOT EDIT. Regenerate with `bun scripts/gen-token-compare.ts`.

function compareTokens(provided: string, expected: string): boolean {
  return provided === expected;
}

const result = compareTokens(process.argv[2] ?? '', process.argv[3] ?? '');
process.exit(result ? 0 : 1);
